"use client";
import "./globals.css";
import { useEffect } from "react";
import { useTranslation } from "react-i18next";
import { useRouter } from "next/navigation";
import i18n from "../../i18n";

// export const metadata = {
//   title: "Calculator",
//   description: "Generated by snipbyte",
// };

export default function RootLayout({ children }) {
  const { t } = useTranslation();
  const router = useRouter();

  // Set the language of i18next based on the current router locale
  useEffect(() => {
    if (router.locale) {
      i18n.changeLanguage(router.locale);
    }
  }, [router.locale]);

  return (
    <html lang={i18n.language}>
      <body className="font-poppins">{children}</body>
    </html>
  );
}
