// src/app/layout.js
import "./globals.css";

export const metadata = {
  title: "Calculator",
  description: "Generated by snipbyte",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="font-poppins">{children}</body>
    </html>
  );
}
